services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: auctiondb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
      
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    networks:
      - app-network  

  auctionservice:
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    image: ${DOCKER_REGISTRY-}auctionservice
    depends_on:
      - postgres
    ports:
      - 7001:7001
    networks:
      - app-network
    environment:
      - ASPNETCORE_URLS=http://*:7001

  searchservice:
    image: ${DOCKER_REGISTRY-}searchservice
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    depends_on:
      - mongodb
    ports:
      - 7002:7002
    networks:
      - app-network
    environment:
      - ASPNETCORE_URLS=http://*:7002

volumes:
  pgdata:
  mongodata:

networks:
  app-network:
    driver: bridge
