services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: auctiondb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
      
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    networks:
      - app-network  

  auctionservice:
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    image: kelarens/auctionservice
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 7001:8080
    networks:
      - app-network
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctiondb

  searchservice:
    image: kelarens/searchservice
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - 7002:8080
    networks:
      - app-network
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=mongodb://admin:mongopw@mongodb
      - AuctionServiceUrl=http://auctionservice

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network  


volumes:
  pgdata:
  mongodata:

networks:
  app-network:
    driver: bridge
